# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-aws-credentials
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        args:
        - -i
        - --max-line-length=120
        - --ignore=E226,E24,W50,W690,E402

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.4.4'  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
        additional_dependencies:
        - locustio==0.14.2
        - boto3==1.11.9
        - numpy==1.18.1
        - prometheus-client==0.7.1
        - cassandra-driver==3.21.0
        - aioboto3==6.4.1

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.1
  hooks:
      - id: commitlint
        stages: [commit-msg]
